name: app_medica
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  intl: ^0.18.1
  get: ^4.6.5
  flutter_staggered_animations: ^1.1.1
  pdf: ^3.10.1
  printing: ^5.10.3
  image_picker: ^0.8.7+4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
